### ISSUE TITLE
Refactor bootstrap service

### ISSUE THREAD

**Issue by manuio** [MainfluxLabs/mainflux#102]

**Comment by manuio** [comment]
Started here: https://github.com/MainfluxLabs/mainflux/pull/103

**Comment by zzokki81** [comment]
After implementation of disallowing things to be connected to more then one channel `UpdateConnections` is not working Like it should. Currently it iterates over `connect` and `disconnect`  and trying to connect multiple channels to  the same thing.

**Comment by manuio** [comment]
Since we introduced unique Things connections bootstrap and provision services were not working because both were creating several channels and connecting them to a same thing. After the introduction of the new `group_id` field it's even more complicated to understand and use these services. Plus, bootstrap service was always strictly related to agent service and demanded a previous configuration of the external device. Having a such power on the firmware would rarely force you to create bootstrap configs and pull them.
Instead, we can simply move any external configuration to the new Channel Profile and try to make it configurable for any device. 

Removing bootstrap and provision service here: https://github.com/MainfluxLabs/mainflux/pull/438
