### ISSUE TITLE
Create Things Profiles and make them assignables to Channels

### ISSUE THREAD

**Issue by manuio** [MainfluxLabs/mainflux#239]
Create a Profile for Things that we can apply to channels so the publisher can redirect messages to the broker depending on the profiles attched to a channel and using NATS topics. Consumers will use proper NATS topics to filter the messages to consume.
Curent consumers where we can apply profiles are  `senml`, `json`, `smtp` and `smpp`.  Some of this profiles can be combined. Some consumers like`json` writer have an additional configuration. We can also add something similar to the senml` profile in order to accetp different time formats and units.

The profile can also hold information about rules or  consumers and writers configs. For that, we need different databases that correspond to a profile type.  `senml_profile` (`id`, `name`, `content_type`), `json_profile` (`id`, `name`, `content_type`,  `time_name`, `time_format`, `time_location`), `smtp_profile` and  `smpp_profile` will be attched to channels with another database with fields: `profile_type`, `channel_id`,  `rule_id`.

**Comment by zzokki81** [comment]
Related Issues:
1. #370
2. #373
3. #375 
4. #383
5. #386
6. #392
7. #393
