### ISSUE TITLE
Missing Url of Auth service in timescale-reader

### ISSUE THREAD

**Issue by voler88** [MainfluxLabs/mainflux#286]
**BUG REPORT**

Trying to get messages from timescale-reader via Bearer JWT.
Get error: {"error":"failed to perform authorization over the entity"}
Getting messages via Thing key is work.

In log see empty value for authGRPCURL:
mainfluxlabs-timescale-reader | {"level":"info","message":"Established gRPC connection to auth via gRPC: ","ts":"2023-09-18T11:41:10.867294355Z"}

Problem: 
Missing default and env values for authGRPCURL and authGRPCTimeout in  https://github.com/MainfluxLabs/mainflux/blob/master/cmd/timescale-reader/main.go and https://github.com/MainfluxLabs/mainflux/blob/master/docker/addons/timescale-reader/docker-compose.yml

**Comment by manuio** [comment]
@voler88 Can you take this one or you prefer if we do it?
