### ISSUE TITLE
Subscribe thing to multiple topics

### ISSUE THREAD

**Issue by voler88** [MainfluxLabs/mainflux#349]
**BUG REPORT**

1. What were you trying to achieve?
Subscribe 1 thing to 2 subtopics.

2. What are the expected results?
{"level":"info","message":"Method create_subscription took 42.090687ms to complete without errors.","ts":"2023-10-30T17:46:16.852458391Z"}
{"level":"info","message":"subscribed with client_id mosquito-client to topics channels/1f85f7a2-e403-4033-b6c8-1133d79e0c5e/messages/test1","ts":"2023-10-30T17:46:16.852675637Z"}
{"level":"info","message":"Method create_subscription took 42.090687ms to complete without errors.","ts":"2023-10-30T17:50:33.235120419Z"}
{"level":"info","message":"subscribed with client_id mosquito-client to topics channels/1f85f7a2-e403-4033-b6c8-1133d79e0c5e/messages/test2","ts":"2023-10-30T17:50:33.235120419Z"}

Subscribe to test1 and test2 subtopics.

3. What are the received results?
{"level":"info","message":"Method create_subscription took 42.090687ms to complete without errors.","ts":"2023-10-30T17:46:16.852458391Z"}
{"level":"info","message":"subscribed with client_id mosquito-client to topics channels/1f85f7a2-e403-4033-b6c8-1133d79e0c5e/messages/test1","ts":"2023-10-30T17:46:16.852675637Z"}
{"level":"warn","message":"Method create_subscription took 23.929062ms to complete with error: entity already exists : ERROR: duplicate key value violates unique constraint \"subscriptions_client_id_key\" (SQLSTATE 23505).","ts":"2023-10-30T17:50:33.235120419Z"}
{"level":"error","message":"failed to subscribe: subscription already exists","ts":"2023-10-30T17:50:33.23528708Z"}
docker exec -ti mainfluxlabs-mqtt-db psql -Umainflux subscriptions -c 'SELECT * FROM subscriptions'
 subtopic |              channel_id              |               thing_id               |    client_id    |  status   |     created_at     
----------+--------------------------------------+--------------------------------------+-----------------+-----------+--------------------
 test1    | 1f85f7a2-e403-4033-b6c8-1133d79e0c5e | 45b2b3e2-b437-4404-bada-2de1f60dcbcc | mosquito-client | connected | 1698687976.8097067
(1 row)

4. What are the steps to reproduce the issue?
Subscribe to test1 and then test2 subtopics from mosquitto_sub

5. In what environment did you encounter the issue?
docker compose on test server

6. Additional information you deem important:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718063

**Comment by manuio** [comment]
@voler88 `ERROR: duplicate key value violates unique constraint "subscriptions_client_id_key"` If I remember well client_id has to be unique per connection (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718028). Eventually it can be removed here: https://github.com/MainfluxLabs/mainflux/blob/master/mqtt/postgres/init.go#L52

**Comment by voler88** [comment]
And hence one subscription per connection?

**Comment by manuio** [comment]
Right, this is not correct. TBH, the mqtt-adapter need some refactoring. Also, mproxy should be improved to pass more data to Connect and Disconnect handlers: https://github.com/mainflux/mproxy/blob/master/pkg/session/stream.go#L106 We recently reverted Connected/Disconnected status because of handlers limitations, that's why client_id was unique. 
But it's wrong, I'll remove it and investigate mproxy to have a proper subscribtion status per topic and client_id. For now Subscription list will show subscription Connected unless you properly unsubscribe.
