### ISSUE TITLE
SQL error from Timescale Reader

### ISSUE THREAD

**Issue by voler88** [MainfluxLabs/mainflux#389]
**BUG REPORT**

1. What were you trying to achieve?
Multiple time get messages:
GET https://my_server/reader/messages?name=my_name&limit=1000

2. What are the expected results?
Messages

3. What are the received results?
Sometimes I get this errors in Timescale Reader and DB
`{"level":"warn","message":"Method list_all_messages took 371.133µs to complete with error: failed to read messages from database : ERROR: syntax error at or near \"WHERE\" (SQLSTATE 42601).","ts":"2024-02-14T16:07:18.466382729Z"}`
```
2024-02-14 16:09:50.245 UTC [689495] STATEMENT:  SELECT * FROM messages  WHERE time < $1 WHERE name = $2 AND time >= $3 ORDER BY time DESC LIMIT $4 OFFSET $5;
2024-02-14 16:10:01.523 UTC [689495] ERROR:  syntax error at or near "WHERE" at character 41
```

4. What are the steps to reproduce the issue?
Default instalation with timescale addon.

6. In what environment did you encounter the issue?
Version 0.16.3

7. Additional information you deem important:
Perhaps the problem is missng "AND" op for "to" case in function "fmtCondition"?
https://github.com/MainfluxLabs/mainflux/blob/0.16.3/readers/timescale/messages.go

**Comment by manuio** [comment]
@voler88 Looks like you are right. Would you like to take this one?
