### ISSUE TITLE
mainfluxlabs CLI "messages send" command is posting to the wrong endpoint

### ISSUE THREAD

**Issue by Sidahmeders** [MainfluxLabs/mainflux#436]
when I run the following command using (**MF_RELEASE_TAG=0.19.0**):
```
 mainfluxlabs-cli messages send <channel_id.subtopic> <JSON_string> <thing_key>
```
I see the following logs:
```
mainfluxlabs-ui | [ip] - [time] "POST /http/channels/<channel_id>/messages/ HTTP/1.0" 405 174 "-" "Go-http-client/1.1" "172.22.0.1"
```
also when I checked the docs [api/send-messages](https://mainfluxlabs.github.io/docs/api/#send-messages) I found this command:
```
curl -s -S -i -X POST ... -H "Authorization: Thing <thing_key>" http://localhost/http/channels/<channel_id>/messages -d ....
```
and as you can see the following endpoint will not work `http://localhost/http/channels/<channel_id>/messages`. To resolve this, we need to omit the `http` segment following `localhost` in the path. Failure to do so will result in the same error encountered when using the CLI messages `send` command.

**Comment by manuio** [comment]
The `/http` prefix is used by the nginx proxy to redirect to the http-adapter since there are other services sharing `/chanels` prefix.  It should work using `http://localhost/http/channels/<channel_id>/messages`.
