### ISSUE TITLE
Thing Identification Failure Causing MQTT Data Transmission Errors

### ISSUE THREAD

**Issue by linhoulong** [MainfluxLabs/mainflux#443]
---

**BUG REPORT**

1. **What were you trying to achieve?**
   - I was trying to connect a Thing to a Channel in Mainflux and then view the connected Thing's details through the Mainflux UI.

2. **What are the expected results?**
   - After connecting the Thing to the Channel, I expected to be able to view the Thing's details page in the Mainflux UI without encountering any errors.

3. **What are the received results?**
   - Upon attempting to view the Thing's details page, I received a failure message: "failed to fetch file paths" along with an Error 404 - Not Found.

4. **What are the steps to reproduce the issue?**
   - Step 1: Connect a Thing to a Channel via the Mainflux UI.
   - Step 2: Navigate to the Thing's details page.
   - Step 3: Encounter the error message as described.

5. **In what environment did you encounter the issue?**
   - I encountered this issue in the Mainflux UI, and the problem also affected my Python script using the MQTT protocol to send data to Mainflux.

6. **Additional information you deem important:**
   - Despite the UI error, the relationship between the Thing and Channel is correctly reflected in the `group_things` and `connections` tables in the database.
   - The MQTT connection error logs are as follows:
     ```
     mainfluxlabs-mqtt  | {"level":"info","message":"Accepted new client",ts":"2024-04-24T13:08:45.34515609Z"}
     mainfluxlabs-things | {"level":"warn","message":"Method identify for token 22bf138f-87c8-408b-b299-0e442d69bce4 and thing [thing ID] took 661.193µs to complete with error: entity not found : sql: no rows in result set.",ts":"2024-04-24T13:08:45.371181758Z"}
     mainfluxlabs-mqtt  | {"level":"error","message":"disconnected client_id 7dbe7b0e-e7a5-4a78-8b0b-327a1eab7022 and username 7dbe7b0e-e7a5-4a78-8b0b-327a1eab7022",ts":"2024-04-24T13:08:45.371457417Z"}
     mainfluxlabs-mqtt  | {"level":"warn","message":"Broken connection for client: 7dbe7b0e-e7a5-4a78-8b0b-327a1eab7022 with error: failed proxying from MQTT broker to MQTT client : rpc error: code = NotFound desc = entity not found : sql: no rows in result set",ts":"2024-04-24T13:08:45.371725048Z"}
     ```
![屏幕截图 2024-04-24 211929](https://github.com/MainfluxLabs/mainflux/assets/97341735/9e1354be-2d18-4d8c-ad02-ea70647fe360)
![屏幕截图 2024-04-24 212045](https://github.com/MainfluxLabs/mainflux/assets/97341735/1d927595-7a54-4ad4-92be-cf4d25ccff2f)

I kindly request assistance in resolving this issue so that the Thing details can be fetched successfully, and the MQTT connection is stable for data transmission.

Best regards,

**Comment by linhoulong** [comment]
the  version is 0.17.0

**Comment by manuio** [comment]
0.17.0 is deprecated. Use version 0.19.0 and remove all volumes before because it's not backward compatible.

**Comment by Sidahmeders** [comment]
does anyone run into the following error on  **MF_RELEASE_TAG=0.19.0** when you register or try to login through `mainfluxlabs/ui:0.19.0`?
```
Request URL:
http://localhost:3000/tokens
http://localhost:3000/register

Request Method: POST
Status Code: 405 Not Allowed
Remote Address: [::1]:3000
Referrer Policy: strict-origin-when-cross-origin
```

here is my nginx config:
```
http {
    include snippets/http_access_log.conf;
        ....
        ....
        server {
        listen 80 default_server;
        listen [::]:80 default_server;
        listen 443 ssl http2 default_server;
        listen [::]:443 ssl http2 default_server;

        include snippets/ssl.conf;

        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Methods '*';
        add_header Access-Control-Allow-Headers '*';
        ....
        ....
        # Proxy pass to users service
        location /svcusers/ {
            include snippets/proxy-headers.conf;
            proxy_pass http://users:${MF_USERS_HTTP_PORT}/;
        }
        location ~ ^/(register|users|tokens|password) {
            include snippets/proxy-headers.conf;
            proxy_pass http://users:${MF_USERS_HTTP_PORT};
        }
        ....
        ....
```

**Comment by manuio** [comment]
Port 3000 is used internally. The UI port is the default 80 port. Use `http://localhost` instead

**Comment by manuio** [comment]
@Sidahmeders Can we close the issue?
