### ISSUE TITLE
NATS support request-reply pattern, why we still need gRPC?

### ISSUE THREAD

**Issue by 04116** [MainfluxLabs/mainflux#456]
https://docs.nats.io/nats-concepts/core-nats/reqreply
Hi team, can anyone pls explain to me?

**Comment by manuio** [comment]
I'm not sure to understand the question... We use gRPC for the internal services communication.  NATS is used as internal messages bus between protocol adapters and consumers.

**Comment by 04116** [comment]
hi @manuio 
NATS with request-reply can be use for internal services communication, where instance of service A want to send request to one of instance of service B and expect an synchronus response.

They both use stateful connection, have builtin load balancing feature, request/response can defined use protobuf,...
So why not only use NATS? To have leaner tech stack,...

Are NATS request-reply not yet stable? Or
We need feature source code service generation of gRPC?

p/s: I'm not yet have much experiences with both.

**Comment by manuio** [comment]
@04116 gRPC is client-server while NATS is pub-sub. The advantage having a server is that you can access from any service or even from the outside world without having to change the service receiving the request. With NATS it would be more complicated to access from the outside and you would need to always implement the request-reply in every service. With gRPC you only need a client. Also, grPC has more functionalities related to the security. And last but not least, it's already done and I don't see any advantage starting with NATS now.

**Comment by manuio** [comment]
Closing this one

**Comment by 04116** [comment]
thank you, got it
> And last but not least, it's already done and I don't see any advantage starting with NATS now

I just asking about the design decision already made
