### ISSUE TITLE
Create RetrieveByIDs method in users service

### ISSUE THREAD

**Issue by manuio** [MainfluxLabs/mainflux#70]
Create a method that returns users for given IDs. This method can be used as example: https://github.com/MainfluxLabs/mainflux/blob/master/things/postgres/things.go#L179

**Comment by zzokki81** [comment]
Resolved #73

**Comment by zzokki81** [comment]
Method was already present in user repository so there is no need to add new one.

**Comment by manuio** [comment]
Method renamed here: https://github.com/MainfluxLabs/mainflux/pull/73
